services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/php/DockerfileLaravel
    container_name: laravel_backend_app
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www:z
    networks:
      - app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: projourney_2
      DB_USERNAME: root
      DB_PASSWORD: root

  frontend:
    build:
      context: ./frontend_react
      dockerfile: ../docker/vite/DockerfileVite
    container_name: vite_frontend_app
    volumes:
      - ./frontend_react:/app:z
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app

  nginx:
    image: nginx:latest
    container_name: nginx_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www:z
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:z
    depends_on:
      - backend
    networks:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql_app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projourney_2
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql:z
    networks:
      - app

volumes:
  mysql_data:

networks:
  app:
