
# Este arquivo resolve problema de desencontro entre o caminha de 
# diretórios real, que o Nginx usa para armazenar os arquivos 
# estáticos da aplicação SPA frontend, e o caminho "virtual" 
# definido na alpicação que é gerado no build da mesma, usando ALIAS. Foi
# definido que o aplicação SPA frontend terá domínio 
# "www.example.com/spa", onde "/spa" é o caminho virtual que será 
# usado para diferenciar das das rotas da UI Laravel que tem no 
# seu domínio a '/', facilitando o a diferenciação entre as rotas 
# da UI Laravel+Inertia e das rotas UI React. 
#   O real motivo dessa configuração é porque o projeto pretende 
# ser usado com acesso via proxy reverso, dividindo a mesma base de
# domínio/URL.

server {
    listen 80;
    root /usr/share/nginx/html;  # raiz do filesystem
    index index.html;
    
    location /spa/assets/ {
        alias  /usr/share/nginx/html/assets/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /spa/image {
        alias  /usr/share/nginx/html/image/;
    }

    # Qualquer outra rota /spa/*: SPA fallback para React Router
    location /spa/ {
        try_files $uri /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}